### ISSUE TITLE
Удалить устаревший код: OnBnClickedOpen() - много лишних действий со строками

### ISSUE THREAD

**Issue by Kerminator1973** [Laserist202277/Project1#13]
Данные из файла считываются, но не используются:

```cpp
CFile file(fileDialog.GetPathName(), CFile::modeRead | CFile::shareDenyNone);

// Открываем файл содержащий скрипт и считываем его содержимое в память
dwLength = size_t( file.GetLength() );
pDocument = new unsigned char[dwLength + 1];
file.Read(pDocument, (UINT)dwLength);
pDocument[dwLength] = 0;
bSuccess = TRUE;
```

Кусок экспериментального кода, который не используется.

В действительности, имеет смысл сохранять подкаталог, в котором находится выбранный файл, чтобы использовать его в качестве стартовой точки при следующем запуске приложения.

**Comment by Laserist202277** [comment]
Часть почищена, оставил, то что может пригодиться, возможно это надо убрать, также на кнопке New весит вот такой кусок:
// Это нужно будет сделать, но потом...
		/*
		CFileDialog fileDialog1(TRUE);
		// Если имя файла ещё не было указано, то используем указанный "подкаталог по умолчанию"
		CString strFilenamewrite;
		CString m_csAdmPKBasePath1;
		fileDialog1.m_ofn.lpstrInitialDir = strFilenamewrite;
		if (fileDialog1.DoModal() == IDCANCEL)
		return;
		int nPos = strFilenamewrite.ReverseFind('\\');
		if (nPos >= 0) {
		strFilenamewrite.Delete(nPos, strFilenamewrite.GetLength() - nPos);
		}

		// Осуществляем отправку документа на сервер
		CFile* pFile = NULL;
		unsigned char* pDocument = NULL;
		size_t dwLength = 0;

		BOOL bSuccess = FALSE;
		TRY
		{
		pFile = new CFile(fileDialog1.GetPathName(), CFile::modeWrite | CFile::shareDenyNone);
		// Открываем файл содержащий скрипт и считываем его содержимое в память
		dwLength = size_t(pFile->GetLength());
		pFile->Write(pDocument, (UINT)dwLength);
		pDocument[dwLength] = 0;
		bSuccess = TRUE;
нужен ли он?

**Comment by Kerminator1973** [comment]
Лишний код удалён, замечание отработано.
