### ISSUE TITLE
Метод SaveItemsData работает до номиналов, на сохранение в новый файл старого файла NewBlackList, но не работает сохранение нового при создании на кнопку NEW

### ISSUE THREAD

**Issue by Laserist202277** [Laserist202277/Project1#16]
Насколько я понимаю, это из-за типов, так как типы rt только в файле NewBlist. Похоже надо создавать 2 разных метода для сохранения старого файла в новый файл, и сохранения нового дерева в файл, при этом делать проверку на то новое это дерево ил нет

**Comment by Kerminator1973** [comment]
Разницы, по сути, никакой нет. Если ты создаёшь новый файл, ты должен указать в ключах открытия, что это файл создаётся в режиме "create + write + binary". Если пишешь в новый файл, то точно так же открываешь файл, но в режиме "override + write + binary".

**Comment by Kerminator1973** [comment]
Отработано. Закрываю.
