### ISSUE TITLE
Получение данных при сохранении, так как в Composer в методах addCurrency(char* currencyName) и тд, требует аргумент для вызова метода, проблема.

### ISSUE THREAD

**Issue by Laserist202277** [Laserist202277/Project1#17]
Проблема в том, что если я делаю const wchar_t* currencyName = pItem->GetItemText().c_str(); а он просит wchar_t так как мы работаем с Unicode, чтобы вытащить данные для сохранения данного элемента, надо менять весь Composer в типы wchar_t, но тогда надо и менять pData, элемент структуры typedef struct tagBlackListRecordIntegrated, что делать? Начал менять Composer, но пока не коммичу, иначе код поедет, лучше потом ещё раз сделаю.

**Comment by Kerminator1973** [comment]
Ты не можешь использовать pItem->GetItemText() для получения валюты, т.к. этот метод возвращает комбинированную строку с комментарием. У тебя есть универсальный метод для получения комментариев: `std::wstring GetComment()`. А в BlackListCurrency у тебя есть ещё один метод - `std::wstring GetCurrency()`. Соответственно, для поля Currency ты используешь - GetCurrency(), а для поля Comment ты получает Unicode через GetComment() и преобразовываешь его в ANSI. Это позволяет тебе полноценно заполнить tagBlackListRecordIntegrated, как ты уже делал это в своём тестовом примере.
