### ISSUE TITLE
Человеко-ориентированность пользовательского интерфейса

### ISSUE THREAD

**Issue by Kerminator1973** [Laserist202277/Project1#18]
По результатам обсуждения пользовательского интерфейса прототипа редактора с Данил Евгеньевичем, главное замечание - специалисту, который не знаком с приложением будет не понятно, что такое "Root", "Substring" и "Left". Необходимо заменить эти термины на более понятные специалистам, которые будут настраивать "черный список".

"Substring" и "Left" - это сущности реализации системы хранения. Для пользователей должны быть другие термины, например, "Шаблон серийного номера".

Слово "Root" - типовое слово используемое программистами, которое тоже не несёт смысла для банковских сотрудников. Тут уже нужно нам подумать, на что заменить, например: "Все валюты".

Планируется переслать версию приложения Егору и, возможно, Артуру, чтобы они посоветовали, какие термины правильно использовать.

**Comment by Kerminator1973** [comment]
Связано с #37.

Выяснили, что substring и leaf - это части одной сущности "серийный номер". Переделывааем пользовательский интерфейс.

**Comment by Kerminator1973** [comment]
Диалоги substring и leaf объединены в один диалог Serial Number.

**Comment by Kerminator1973** [comment]
Что дальше?

В полях ввода "год выпуска" и "номинал" добавить технику Subclassing-а, чтобы разрешить вводить только цифры.

При открытии диалога, фокус ввода должен стоять сразу же на строке редактирования, а не на кнопки "OK".

**Comment by Kerminator1973** [comment]
Поля ввода "год выпуска" и "номинал" теперь имеют свойство "Number" установленное в **true**. Раньше пришлось бы использовать SubclassDlgItem() и обрабатывать в CEdit событие OnChar(). Но библиотека MFC, таки, развивалась в последние годы (2013! :-)

**Comment by Kerminator1973** [comment]
В диалоге ввода номиналов, необходимо добавить две переменные для хранения номинала и года выпуска при включении/выключении флага "Any". Если при входе в диалог номинал, или год выпуска установлены в "Any", то отключении галки "Any" имеет смысл подставлять значения по умолчанию: 100 и 1995.

**Comment by Laserist202277** [comment]
постараюсь выполнить

**Comment by Kerminator1973** [comment]
Добавил строку поиска элемента и соответствующую логику.

Редактор кажется уже вполне вменяемым.

**Comment by Kerminator1973** [comment]
На данный момент, осталось сделать следующие штуки:

Ещё нужно сделать проверку количество вложенных подстрок при добавлении новой подстроки.

В диалоге ввода номиналов, необходимо добавить две переменные для хранения номинала и года выпуска при включении/выключении флага "Any". Если при входе в диалог номинал, или год выпуска установлены в "Any", то при отключении галки "Any" имеет смысл подставлять значения по умолчанию: 100 и 1995.

**Comment by Kerminator1973** [comment]
Добавлены значения по умолчанию для полей в диалоге "Номиналы"

**Comment by Kerminator1973** [comment]
Замечание отработано в полном объёме.
