### ISSUE TITLE
Можно формировать текст для ветки дерева внутри BlackListXXX, чтобы унифицировать код

### ISSUE THREAD

**Issue by Kerminator1973** [Laserist202277/Project1#2]
Можно добавить виртуальный метод GetItemText() в класс BlackListItem и реализовать его уникальным образом для каждого произвольного класса. При формировании дерева, можно вызывать один метод - GetItemText() для объекта любого класса, производного от BlackListItem и использовать полученную строку для добавления/изменения текста в ветке дерева объектов чёрного списка:

```cpp
class BlackListItem
{
public:
	BlackListItem();
	int GetType();
	virtual std::wstring GetItemText();
```

**Comment by Kerminator1973** [comment]
Поясню, что это тебе даст. В методе CBlackListDlg::LoadBlackList() у тебя есть while() с кучей if-ов. Если у тебя будет реализован виртуальный метод GetItemText(), то ты сможешь убрать все if-ы внутри этого while - у тебя останется, буквально 3-5 строк кода. 

По сути, вместо if-ов будет работать таблица vtables, в которой хранится информация о фактической реализации для каждого конкретного класса в контейнере.

**Comment by Kerminator1973** [comment]
Можно пойти ещё дальше и разместить вызов диалогов для создания и редактирования объектов классов, производных от CBlackListItem внутри самих производных классов. В этом случае, тебе не нужно будет явным образом работать с типом класса, т.е. использовать GetType() - ты просто будешь вызывать виртуальный метод DoEdit() для объекта, который получаешь из GetItemData().

**Comment by Laserist202277** [comment]
Пока что проинициализирован метод virtual std::wstring GetItemText(); , что делать дальше не понятно

**Comment by Kerminator1973** [comment]
Дальше нужно реализовывать этот метод в производных классах. Для BlackListDemonination тебе нужно будет создать wstringstream, поместить в него переменные класса через << и вернуть его, используя метод .str().

Тем, где ты формируешь дерево, ты уже не используешь wstringstream для каждого типа элементов дерева, а вызываешь метод GetItemText() для указателя на BlackListItem.

**Comment by Kerminator1973** [comment]
Всё это делается ради того, чтобы тебе не нужно было работать с полями производных от BlackListItem типом.

Было:

```cpp
CString SubResult(dialog3.newSubString);
if (dialog3.SubStringComment != "")
{
	SubResult += "//";
}
SubResult += dialog3.SubStringComment;
HTREEITEM hSubItem = m_Tree.InsertItem(LPWSTR(LPCTSTR(SubResult)), m_hLastPopupTreeItem);
m_Tree.SetItemData(hSubItem, (DWORD_PTR)pItem4);
```

Стало:

```cpp
auto pItem4 = new BlackListSub("B490", LPWSTR(LPCTSTR(dialog3.newSubString)), 5);
HTREEITEM hSubItem = m_Tree.InsertItem(pItem4->GetItemText().c_str(), m_hLastPopupTreeItem);
m_Tree.SetItemData(hSubItem, (DWORD_PTR)pItem4);
```

**Comment by Kerminator1973** [comment]
Успешно сделано
