### ISSUE TITLE
если делаю сохранение сабстрингов также как номиналов и каренси и рут, приложение вылетает

### ISSUE THREAD

**Issue by Laserist202277** [Laserist202277/Project1#21]
```cpp
case rt_substring:
	{
		 char* SubComment = "Comment";
		 wchar_t* substring = _T("B490");
		 container.addSubString(substring, SubComment);
	}
```
скорее всего, это из-за того, что после номиналов может быть лиф, и здесь также не понимаю, как вытащить данные, так как в конструкторе addSubString также 2 аргумента substring и Comment оба типа char

**Comment by Kerminator1973** [comment]
Т.е. сейчас проблема только с SubString?

**Comment by Kerminator1973** [comment]
Одна из проблем - ты не используешь break в конце обработчика case. Если break-а нет, то обработка продолжается и в следующем case и так - до завершения switch.

```cpp
case rt_substring:
{
	char* SubComment = "Comment";
	wchar_t* substring = _T("B490");
	container.addSubString(substring, SubComment);
	break;
}
```

**Comment by Kerminator1973** [comment]
Твой код падает вот на этой строке:

```cpp
strncpy_s(SUBelem.Comment + 1, subNameLen + 1, SubComment, subNameLengthInHeader);
```

subNameLen - это размер буфера в который ты копируешь и ты указываешь 5, а subNameLengthInHeader - это количество байт для копирования - и у тебя их 6. Как минимум, эта операция не будет завершена успешно.

**Comment by Kerminator1973** [comment]
Славик! Нужно смотреть, что делает (и не делает) Сергей в его библиотеке при добавлении нового блока:

```cpp
tBlackListRecord* cSNBlackList::addRecord (tBlackListRecordIntegrated* newRecord, int* Errcode)
{
...
    if ((iActualLength + newRecord->pHdr->RecordLength) > iMaxLength) {   // Ошибка: не хватает памяти
...
        tmp = (char*)(((char*)pCurrRecord) + pCurrRecord->RecordLength);
...
    iActualLength += pCurrRecord->RecordLength;
    return pCurrRecord;
}
```

Ключевое поле - **RecordLength**. Как можно увидеть - в коде он не заполняет RecordLength, а только использует его. Т.е. Сергей считает, что ты точно рассчитаешь длину всего блока. Но ты так не делаешь...

Вот твой корректный код для root-а:

```cpp
void Composer::addRoot(){
...
	int _commentLength = 6;
...
	rootElement.pHdr->RecordLength = 10 + _commentLength;
...
}
```

Ты включил в общую длину блока длину комментария.

А вот не корректный код добавления подстроки:

```cpp
const int nomNameLen = strlen(nomName);	// Длина строки
// Длина строки с байтом длины и выравниваем по двум байтам
const int nomNameLengthInHeader = nomNameLen + 1 + (nomNameLen % 2 != 0 ? 0 : 1);	
...
Nom1.pHdr->DataLen = sizeof(tBnDenIss);
Nom1.pHdr->BlockLength = 0;
Nom1.pHdr->RecordLength = RECORD_HDR_SIZE + nomNameLengthInHeader + Nom1.pHdr->DataLen;
```

Фактически ты отводишь место только для:

```cpp
typedef struct tagBlackListRecord
{
    unsigned int       RecordLength;    // Длина записи
    unsigned int       BlockLength;     // Длина блока
    unsigned char      Type;            // Тип записи
    unsigned char      DataLen;         // Длина поля данных
    без него --> short              D;               // Адрес этого поля используется как адрес поля данных
} tBlackListRecord;

typedef struct tagBnDenIss
{
    unsigned long      Denom;           // Номинал
    unsigned short     Year;            // Год эмиссии
    unsigned char      Version;         // Версия эмиссии
    unsigned char      dummy;           // для выравнивания
} tBnDenIss;
```

И ещё для чего-то, что ты называешь "длина номинала" (nomNameLen).

Ошибок, как минимум, две:

1. Никакой длины номинала быть не должно, т.к. номинал - это поле Denom структуры tagBnDenIss. Т.е. тебе нужно преобразовать строку к unsigned long
2. Не учитывается длина поля комментария

**Comment by Kerminator1973** [comment]
Вроде бы проблема решена.
