### ISSUE TITLE
при записи комментария на русском для веток currency и nominal вылетает access violation, причём пишет ошибка memcpy.asm not found

### ISSUE THREAD

**Issue by Laserist202277** [Laserist202277/Project1#27]

**Comment by Kerminator1973** [comment]
Не удалось воспроизвести проблему при записи Currency, но при добавлении комментария на кириллице в Nominal, проблема действительно возникает.

**Comment by Kerminator1973** [comment]
Под отладчиком можно войти в код Сергея и увидеть, что проблема возникает при копировании строки:

```cpp
   memcpy(((char*)(&pCurrRecord->D) + newRecord->pHdr->DataLen), newRecord->Comment, newRecord->Comment[0]+1);
```

В поле "Comment" первый байт должен содержать длину комментария.
