### ISSUE TITLE
 При нажатии кнопки выхода из меню работы с чёрным списком не появляется запрос о сохранении полученных результатов/внесенных изменений. Как я понимаю просто сделать диалог: сохранить данные?

### ISSUE THREAD

**Issue by Laserist202277** [Laserist202277/Project1#28]

**Comment by Kerminator1973** [comment]
Нет, нужно сделать специальную переменную IsDirty, которая будет изначально установлена в false, а при изменении данных, добавлении веток, удалении веток, она будет устанавливаться в true. В обработчике сообщение OnClose() нужно проверять значение этой переменной и выводить справочный message box, если изменения были сделаны.

Я сам это обращение отработаю.

**Comment by Kerminator1973** [comment]
Добавлен флаг m_IsDirty и проверка при выходе из диалоге без сохранения. В случае изменения требуется подтверждение.
