### ISSUE TITLE
Substrings и Leaves попали на один уровень...

### ISSUE THREAD

**Issue by Kerminator1973** [Laserist202277/Project1#32]
Считывает корректных файл, сохраняем его из редактора и Substrings и Leaves оказываются на одном уровне, что некорректно.

**Comment by Kerminator1973** [comment]
![TestErrorMix](https://user-images.githubusercontent.com/32524563/82244522-093f6280-994a-11ea-92c1-32ea56e5554f.png)
Вот пример ошибки

**Comment by Laserist202277** [comment]
В последнем коммите проблема решена.
