### ISSUE TITLE
при открытии файла в hex-редакторе в конце каждой записи, несколько байт мусора, скорее всего ошибка с размером

### ISSUE THREAD

**Issue by Laserist202277** [Laserist202277/Project1#35]

**Comment by Kerminator1973** [comment]
Скорее всего, Сергей пишет о множестве символов 'H':
![Garbage](https://user-images.githubusercontent.com/32524563/82724936-31c8b300-9ce2-11ea-89ca-eda616e8df39.png)

**Comment by Kerminator1973** [comment]
Этот мусор похож на косяки в вычислением заголовка полей substrings и leaves.

Ещё одна проблема - порезан комментарий, см.: **Comme** вместо "Comment".

**Comment by Kerminator1973** [comment]
Символ 'H' - это код "cd", которым Microsoft заполняет не проинициализированную память в DEBUG-режиме.

Для substrings проблема, похоже, в коде Сергея, который не скопировал завершающий ноль - потом нужно будет посмотреть его код.

**Comment by Kerminator1973** [comment]
Переписа AddLeaf() и AddSubstring()

**Comment by Kerminator1973** [comment]
Рассогласование с кодом Сергея:

```cpp
if (newRecord->pHdr->DataLen > 0)  // если есть данные, копируем данные
        memcpy((char*)(&pCurrRecord->D), newRecord->pData, (newRecord->pHdr->DataLen));
memcpy(((char*)(&pCurrRecord->D) + newRecord->pHdr->DataLen), newRecord->Comment, newRecord->Comment[0]+1);
```

Конкретная проблема вот с этой строкой:

```
memcpy(((char*)(&pCurrRecord->D) + newRecord->pHdr->DataLen), newRecord->Comment, newRecord->Comment[0]+1);
```

**Comment by Kerminator1973** [comment]
OK. С комментариями в substring и leaf я разобрался - программа Сергея корректно считывает эти данные. Теперь нужно обеспечить, чтобы приложение Сергея считывало все остальные поля корректно, а потом нужно будет скорректировать собственный Parser.

**Comment by Laserist202277** [comment]
а наше приложение? Я когда открыл сохраненное у меня поехал unicode

**Comment by Kerminator1973** [comment]
Не всё сразу... Нужно сделать много рутинной работы очень аккуратно

**Comment by Kerminator1973** [comment]
![SubstringTextError](https://user-images.githubusercontent.com/32524563/82731558-7408e900-9d10-11ea-8721-cbcead1f1ef1.png)
Следующая проблема - отображение текста "Substring".

**Comment by Kerminator1973** [comment]
OK. Теперь в приложении Сергея всё выглядит **nice**.

Дальше посмотрим, что происходит при чтении файлов в нашем редакторе черного списка.

**Comment by Kerminator1973** [comment]
Да и у нас всё выглядит **nice**.
