### ISSUE TITLE
Добавить возможность добавления Leaf к номиналам

### ISSUE THREAD

**Issue by Laserist202277** [Laserist202277/Project1#37]

**Comment by Laserist202277** [comment]
добавлена возможность добавления к номиналам ещё и Leaf на кнопку addItem, но возникает теперь подряд 2 диалоговых окна, почему-то, как в popup menu добавить возможность добавления к номиналам ещё и leaf, пока не понял, Макс, посмотри плиз, когда время будет

**Comment by Kerminator1973** [comment]
Для меня самого: посмотреть проблему Славика, переписать обращение

**Comment by Laserist202277** [comment]
сделал добавление leaf и substring к номиналам через popupmenu

**Comment by Laserist202277** [comment]
Также сделана возможность добавления и лиф и сабстринг через кнопку addItem, вылетает 2 диалоговых окна, но если не ввести сабстринги в первом диалоге, то он просит ввести строку, возможно можно как-то получше сделать, а не 2 диалоговых окна подряд

**Comment by Kerminator1973** [comment]
Конечно же будет два диалога, т.к. ты редактируешь именно два элемента:

```cpp
case rt_den_iss:
	DoEditElement(new BlackListSub(_T("")));
	DoEditElement(new BlackListLeaf(_T("")));
	break;
```

**Comment by Kerminator1973** [comment]
Вообще не так нужно делать. Нужно отказываться от отдельных сущностях leaf и substring и вводить только одну "элемент серийного списка". Если "элемент серийного списка" не последний, то при записи в файл - он будет substring, а если последний, то Leaf...

**Comment by Kerminator1973** [comment]
OK. Я это реализую чуть позже...

**Comment by Kerminator1973** [comment]
У одного substring-а может быть несколько leaves. Т.е. нормальной является ситуация, когда в бинарном файле указывается: substring -> leaf -> leaf -> left. Это типовая ситуация.

Не типовая ситуация, когда дерево должно выглядеть как: substring -> substring -> leaf -> leaf. По всей видимости, в этом случае leaves относятся к последнему substring и именно end позволяет вернуться на уровень выше. И мы это видим в примере файла "NewBlist.blist": когда после end-а, X12345678G должен оказаться на том же уровне, что и "B490".

Таким образом, нам нужно решить несколько больших задачи:

1. Корректно извлекать данные из бинарного файла с использованием end
2. Сохранять структуру дерева корректно, добавляя end, чтобы указать на завершение очередного уровня
3. Убрать из пользовательского интерфейса элементы типы end
4. Объединить диалоги Substring и Leaf
5. Обеспечить корректное применение операций (popup menu/функциональные кнопки) к дереву

**Comment by Kerminator1973** [comment]
Выполнена корректная визуализация с учётом **end**

**Comment by Kerminator1973** [comment]
![LostEnds](https://user-images.githubusercontent.com/32524563/82904537-48ce0600-9f6b-11ea-8c55-3ed91fe63d29.png)
Потеряно несколько END-ов. Нужно понять условия, в которых мы имеем право их добавлять.

Первое - добавим в log общее количество END-ов в файле.

**Comment by Kerminator1973** [comment]
В нашем обычном файле **NewBlist.blist** есть 10 end-ов. При записи не изменённого файла, у нас должно сохраниться те же десять End-ов.

Если добавлять End-ы ко всем элементам, кроме Leaf, то тогда получается, что у нас есть 11 end-ов... В чём расхождение?

**Comment by Kerminator1973** [comment]
OK. Заработало, но есть расхождение в один End.

**Comment by Kerminator1973** [comment]
Корректный разбор дерева с учётом End-ов и сохранение дерева работает.

Следующий этап - объединить сущности substring и leaf

**Comment by Kerminator1973** [comment]
Алгоритм будет такой: substrings и leaves при чтении транслируются в SerialNumberPart. Вся инфраструктура переписывается над поддержку SerialNumberPart. Если элемент имеет тип SerialNumberPart и у него нет Children, тогда он записывается как leaf, а если у него есть children-ы, то как substring.

Доработка довольно значимая, нужно запланировать под неё 3-4 часа.

**Comment by Kerminator1973** [comment]
#37. Объединены substrings и leaves. Нужно будет потом почистить код - я это сделаю чуть позже.

**Comment by Kerminator1973** [comment]
Нужно будет убрать лишние сущности, удрать диалог для редактирование Leaf, переработать диалог для редактирования Substring, убрать лишние константы из resource.h.

**Comment by Kerminator1973** [comment]
И ещё нужно будет сделать проверку на глубину вложенности substrings...

**Comment by Kerminator1973** [comment]
Успешно отработано.
