### ISSUE TITLE
Ошибка при считывании  Test004 в 3 номинале year в нашей программе отображается 65535, а должна быть *, 65535, это код звёздочки 

### ISSUE THREAD

**Issue by Laserist202277** [Laserist202277/Project1#41]

**Comment by Laserist202277** [comment]
Также 4 номинал, следующий сразу после этого, отображается как 4294967295 в поле denom, а должна быть звёздочка

**Comment by Kerminator1973** [comment]
Да, это важно. Назначу на себя.

**Comment by Kerminator1973** [comment]
Отработано.

Результат мне не полностью понравился, но теперь можно подождать мнения заинтересованных лиц.
