### ISSUE TITLE
Поле "Длина блока" заполняется при добавлении записи типа END, т.е. при закрытии этого блока. Для создания блэклиста нужно выделить достаточно памяти (можно с запасом) и сделать Connect этой памяти к объекту класса cSNBlackList. Затем сделать resetTree. После этого последовательно добавлять записи с помощью addRecord, не забывая про END'ы. По окончании вызвать finishTree, которая вернёт длину либо -1, если где-то забыл END или добавил лишний. Дальше берёшь длину и указатель на выделенную вначале память и записываешь содержимое памяти в файл.

### ISSUE THREAD

**Issue by Laserist202277** [Laserist202277/Project1#42]

**Comment by Kerminator1973** [comment]
Я так понимаю, что это пояснение по замечанию Сергея из его письма: "В поле "Длина блока" всё равно нули. Ты как END добавлял, через addRecord последовательно создавая дерево?"

**Comment by Laserist202277** [comment]
Да, всё верно

**Comment by Kerminator1973** [comment]
Славик! Я посмотрю это обращение внимательно в субботу.

**Comment by Kerminator1973** [comment]
По факту, мы пишем каждый отдельный элемент в файл.

По всей видимости, мы должны писать весь контейнер целиком, предварительно вызвав finishTree().

**Comment by Kerminator1973** [comment]
Открываю оригинальный файл, нажимаю "FIRST REC", затем "NEXT REC" и в окне "Stack" виду ROOT -> USD.

Нажимаю "NEXT BLOCK", USD меняется на RUB.

Вывод - переход на Next Block работает в файлах, сгенерированных Сергеем.

**Comment by Kerminator1973** [comment]
Открываю файл сгенерированный "Text.exe" и повторяю описанную выше последовательность.

Нажимаю "NEXT BLOCK", USD НЕ изменяется на RUB.

Вывод - переход на Next Block не работает в файлах, нашим приложением.

**Comment by Kerminator1973** [comment]
Ошибка устранена.
