### ISSUE TITLE
сли в ветке номинала-эмиссии-версии вложены одновременно substrings и leaves, то в начале должны располагаться substrings, а затем leaves, иначе дерево не соберётся (при сохранении появится ошибка).

### ISSUE THREAD

**Issue by Laserist202277** [Laserist202277/Project1#46]

**Comment by Laserist202277** [comment]
![image](https://user-images.githubusercontent.com/59835561/83889903-1931b180-a754-11ea-9ca9-98c1270934cc.png)

**Comment by Kerminator1973** [comment]
Цитата из письма Сергея:

Не знаю, насколько это правильно или неправильно. Если неправильно, то тогда мне нужно будет внести изменения в класс чёрного списка, чтобы он корректно обрабатывал такую ситуацию. Но тогда сформированные таким образом чёрные списки будут работать только с новыми версиями ПО валидатора, в которых будут учтены эти изменения (т.к. изменения затрагивают и процесс поиска сер. номера в списке).
 
Итого, возможны следующие варианты:
1. Временно, на текущем этапе:  
1.1 либо запретить в принципе создавать записи типа substring
1.2 либо, если в ветке номинала-эмиссии-версии вложены одновременно substrings и leaves, то все leaves, которые не находятся в конце ветки, при формировании дерева перед сохранением вкладывать в пустой substring (содержащий 1 двухбайтовый символ с кодом 0)
2. Отказаться от изменения класса чёрного списка, тогда в будущих версиях редактора необходимо будет следить за тем, чтобы в подобных ситуациях leaves размещались в конце ветки. В этом случае, сформированные чёрные списки будут работать и со старыми версиями ПО валидатора
3. Внести изменения в класс чёрного списка. В этом случае, сформированные таким образом чёрные списки будут работать только с новыми версиями ПО валидатора. Новая версия ПО валидатора, учитывающая эти изменения, будет выпущена вместе с окончанием работ по bootloader'у для платы внешних интерфейсов (ориентировочно к 17.06)

**Comment by Kerminator1973** [comment]
Письмо с предложением по изменению кода:

Добрый день, Сергей!

Огромное СПАСИБО за замечания и комментарии! Особое СПАСИБО – за картинки, которые очень точно поясняют суть проблемы.
Думаю, что в редактор чёрного списка должен учитывать наличие у элемента списка дочерних элементов и сохранять сначала те, у которых дочерние элементы есть. Т.е. мы должны сделать перегруппировку элементов дерева при записи.
Это сделать совсем не сложно – для каждого узла мы можем разделять все элементы на те у которых есть дочерние элементы и те, у которых их нет. Затем мы по очереди сохраняем их, используя тот же самый рекурсивный алгоритм, что и сейчас.
Постараемся сделать это в начале следующей недели.

С наилучшими пожеланиями, Максим Рожков

**Comment by Kerminator1973** [comment]
Попробовал создать тестовый файл с некорректной последовательностью веток - FinishTree() вернул -1.

**Comment by Kerminator1973** [comment]
Связано с #48

**Comment by Kerminator1973** [comment]
Замечание отработано. Нужно отправить Сергею для валидации.

**Comment by Kerminator1973** [comment]
Подтверждение работоспособности от Сергея получено.
