### ISSUE TITLE
Заменить WM_CLOSE на WM_DESTROY

### ISSUE THREAD

**Issue by Kerminator1973** [Laserist202277/Project1#5]
Освобождение памяти выделенной для хранения CBlackListItem было сделано в обработчике события **WM_CLOSE**:

```cpp
BEGIN_MESSAGE_MAP(CBlackListDlg, CDialogEx)
...
	ON_WM_CLOSE()
END_MESSAGE_MAP()
```

К сожалению, WM_CLOSE не вызывается, когда мы выходим из диалога нажав на кнопку IDOK. Соответственно, в прямом потоке память не освобождается.

Нужно попробовать вместо WM_CLOSE обрабатывать WM_DESTROY

**Comment by Laserist202277** [comment]
Заменил

**Comment by Kerminator1973** [comment]
Замечание отработано
