### ISSUE TITLE
Перенести код редактирования параметров BlackListItem в производные классы

### ISSUE THREAD

**Issue by Kerminator1973** [Laserist202277/Project1#8]
Сделать в BlackListItem виртуальный метод DoEdit(). В реализации метода в производных классах включить функционал создания диалогов и работы с ними.

**Comment by Kerminator1973** [comment]
Это имеет смысл сделать для того, чтобы уменьшить количество мест в коде, в которых нужно будет устанавливать флаг IsDirty для контроля того, что содержимое чёрного списка была изменено.

**Comment by Kerminator1973** [comment]
Переработал код создания валюты и номинала (включая диалоги). Создание нового элемента теперь выглядит так:

```cpp
void CBlackListDlg::OnAddCurrency()
{
	DoEditElement(new BlackListCurrency(_T(""), _T("")));
}

void CBlackListDlg::OnAddNominal()
{
	DoEditElement(new BlackListNominal(100, 1995, 255, _T("")));
}
```

**Comment by Laserist202277** [comment]
Выполнено
